const sortcutsId = [
    "shortcut_pencil",
    "shortcut_chooseColor",
    "shortcut_bucket",
    "shortcut_colorSwap",
    "shortcut_eraser",
    "shortcut_line",
    "shortcut_clear",
    "shortcut_bw",
    "shortcut_colorLeft",
    "shortcut_colorRight",
    "shortcut_addFrame",
    "shortcut_frmDuplicateNaN",
    "shortcut_framesNaN_U",
    "shortcut_framesNaN_D",
    "shortcut_frmDeleteNaN",
    "shortcut_rangeNaN_L",
    "shortcut_rangeNaN_R",
    "shortcut_fullScreen",
    "shortcut_downloadGif",
    "shortcut_downloadApng",
    "shortcut_r_first",
    "shortcut_r_second",
    "shortcut_r_third",
    "shortcut_plus",
    "shortcut_minus",
    "shortcut_key",
    "shortcut_signOut",
    "shortcut_penSize1",
    "shortcut_penSize2",
    "shortcut_penSize3",
    "shortcut_penSize4"
];

export { sortcutsId }
